<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

class GenerateTranslations extends Command
{
    protected $signature = 'i18n:generate {--only= : Comma-separated locale codes to (re)generate, e.g. es,fr,ar} {--force : Overwrite already-translated keys instead of only filling gaps}';

    protected $description = 'Machine-generate lang/{locale}/nav.php for every configured locale from lang/en/nav.php, via the free Google Translate endpoint.';

    public function handle(): int
    {
        $source = require lang_path('en/nav.php');
        $locales = collect(config('locales'))->keys()->reject(fn ($code) => $code === 'en');

        if ($only = $this->option('only')) {
            $wanted = collect(explode(',', $only))->map(fn ($c) => trim($c));
            $locales = $locales->intersect($wanted);
        }

        if ($locales->isEmpty()) {
            $this->error('No matching locales to generate (check --only against config/locales.php).');

            return self::FAILURE;
        }

        foreach ($locales as $locale) {
            $this->generateFor($locale, $source, (bool) $this->option('force'));
        }

        return self::SUCCESS;
    }

    private function generateFor(string $locale, array $source, bool $force): void
    {
        $path = lang_path("{$locale}/nav.php");
        $existing = ($force || ! file_exists($path)) ? [] : (require $path);

        $keysToTranslate = $force
            ? array_keys($source)
            : array_diff(array_keys($source), array_keys($existing));

        if (empty($keysToTranslate)) {
            $this->info("[{$locale}] already complete, nothing to do (use --force to regenerate).");

            return;
        }

        $this->info('['.$locale.'] translating '.count($keysToTranslate).' key(s)...');
        $result = $existing;
        $failures = 0;

        foreach ($keysToTranslate as $key) {
            $english = $source[$key];
            $translated = $this->translate($english, $locale);

            if ($translated === null) {
                $this->warn("[{$locale}] failed to translate \"{$key}\" — falling back to English.");
                $failures++;
                $translated = $english;
            }

            $result[$key] = $translated;
            usleep(300_000); // be a polite, slow client against an unofficial endpoint
        }

        // Preserve source key order in the written file, regardless of merge order above.
        $ordered = [];
        foreach (array_keys($source) as $key) {
            $ordered[$key] = $result[$key] ?? $source[$key];
        }

        $this->writeLangFile($path, $ordered);
        $this->info("[{$locale}] wrote ".count($ordered)." keys (".$failures.' fallback(s)) to '.$path);
    }

    private function translate(string $text, string $targetLocale): ?string
    {
        try {
            $response = Http::timeout(10)->get('https://translate.googleapis.com/translate_a/single', [
                'client' => 'gtx',
                'sl' => 'en',
                'tl' => $targetLocale,
                'dt' => 't',
                'q' => $text,
            ]);

            if (! $response->successful()) {
                return null;
            }

            $data = $response->json();
            $segments = $data[0] ?? null;

            if (! is_array($segments) || empty($segments)) {
                return null;
            }

            $translated = implode('', array_map(fn ($segment) => $segment[0] ?? '', $segments));

            return $translated !== '' ? $translated : null;
        } catch (\Throwable $e) {
            $this->warn("Translate request errored for \"{$text}\" -> {$targetLocale}: ".$e->getMessage());

            return null;
        }
    }

    private function writeLangFile(string $path, array $data): void
    {
        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $export = var_export($data, true);
        file_put_contents($path, "<?php\n\n// Machine-generated by `php artisan i18n:generate` from lang/en/nav.php — do not hand-edit.\nreturn {$export};\n");
    }
}
